export const easyMap = [
  [
    {
      enabled: true,
      directions: { north: false, south: false, east: true, west: false },
      entities: [
        {
          name: "Rusty sword",
          value: 3,
          type: "weapon",
          enabled: true,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Demon Knight",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Rusty Key",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Rusty Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
    {
      enabled: true,
      directions: { north: false, south: true, east: false, west: true },
      entities: [
        {
          name: "Rusty sword",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Demon Knight",
          value: 3,
          type: "enemy",
          enabled: true,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Rusty Key",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Rusty Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [
        {
          name: "Rusty sword",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Demon Knight",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Rusty Key",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Rusty Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
  ],
  [
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [
        {
          name: "Rusty sword",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Demon Knight",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Rusty Key",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Rusty Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
    {
      enabled: true,
      directions: { north: true, south: true, east: false, west: false },
      entities: [
        {
          name: "Rusty sword",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Demon Knight",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Rusty Key",
          value: 3,
          type: "item",
          enabled: true,
          symbol: "key",
          seen: false,
        },
        {
          name: "Rusty Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [
        {
          name: "Rusty sword",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Demon Knight",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Rusty Key",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Rusty Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
  ],
  [
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [
        {
          name: "Rusty sword",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Demon Knight",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Rusty Key",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Rusty Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
    {
      enabled: true,
      directions: { north: true, south: false, east: true, west: false },
      entities: [
        {
          name: "Rusty sword",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Demon Knight",
          value: 3,
          type: "enemy",
          enabled: true,
          symbol: "skeleton",
          seen: false,
        },

        {
          name: "Rusty Key",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Rusty Lock",
          value: 3,
          type: "obstacle",
          enabled: true,
          symbol: "lock",
          seen: false,
        },
      ],
    },
    {
      enabled: true,
      directions: { north: false, south: false, east: false, west: true },
      entities: [
        {
          name: "Rusty sword",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Demon Knight",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Rusty Key",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Rusty Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
  ],
];

export const fivebyfive = [
  [
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
  ],
  [
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
  ],
  [
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
  ],
  [
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
  ],
  [
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [],
    },
  ],
];

export const testItems = [
  [
    {
      enabled: true,
      directions: { north: false, south: false, east: true, west: false },
      entities: [
        {
          name: "Sword",
          value: 3,
          type: "weapon",
          enabled: true,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Shield",
          value: 3,
          type: "weapon",
          enabled: true,
          symbol: "shield",
          seen: false,
        },
        {
          name: "Helmet",
          value: 3,
          type: "weapon",
          enabled: true,
          symbol: "armour",
          seen: false,
        },
        {
          name: "Knight",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "knight",
          seen: false,
        },
        {
          name: "Demon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Dragon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "dragon",
          seen: false,
        },
        {
          name: "Treasure",
          value: 3,
          type: "item",
          enabled: true,
          symbol: "ring",
          seen: false,
        },
        {
          name: "Gold",
          value: 3,
          type: "item",
          enabled: true,
          symbol: "coin",
          seen: false,
        },
        {
          name: "Kru",
          value: 3,
          type: "item",
          enabled: true,
          symbol: "key",
          seen: false,
        },
        {
          name: "Gate",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "door",
          seen: false,
        },
        {
          name: "Ramparts",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "castle",
          seen: false,
        },
        {
          name: "Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
    {
      enabled: true,
      directions: { north: false, south: true, east: false, west: true },
      entities: [
        {
          name: "Sword",
          value: 3,
          type: "weapon",
          enabled: true,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Shield",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "shield",
          seen: false,
        },
        {
          name: "Helmet",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "armour",
          seen: false,
        },
        {
          name: "Knight",
          value: 3,
          type: "enemy",
          enabled: true,
          symbol: "knight",
          seen: false,
        },
        {
          name: "Demon",
          value: 3,
          type: "enemy",
          enabled: true,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Dragon",
          value: 3,
          type: "enemy",
          enabled: true,
          symbol: "dragon",
          seen: false,
        },
        {
          name: "Treasure",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "ring",
          seen: false,
        },
        {
          name: "Gold",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "coin",
          seen: false,
        },
        {
          name: "Kru",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Gate",
          value: 3,
          type: "obstacle",
          enabled: true,
          symbol: "door",
          seen: false,
        },
        {
          name: "Ramparts",
          value: 3,
          type: "obstacle",
          enabled: true,
          symbol: "castle",
          seen: false,
        },
        {
          name: "Lock",
          value: 3,
          type: "obstacle",
          enabled: true,
          symbol: "lock",
          seen: false,
        },
      ],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [
        {
          name: "Sword",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Shield",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "shield",
          seen: false,
        },
        {
          name: "Helmet",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "armour",
          seen: false,
        },
        {
          name: "Knight",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "knight",
          seen: false,
        },
        {
          name: "Demon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Dragon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "dragon",
          seen: false,
        },
        {
          name: "Treasure",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "ring",
          seen: false,
        },
        {
          name: "Gold",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "coin",
          seen: false,
        },
        {
          name: "Kru",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Gate",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "door",
          seen: false,
        },
        {
          name: "Ramparts",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "castle",
          seen: false,
        },
        {
          name: "Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
  ],
  [
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [
        {
          name: "Sword",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Shield",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "shield",
          seen: false,
        },
        {
          name: "Helmet",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "armour",
          seen: false,
        },
        {
          name: "Knight",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "knight",
          seen: false,
        },
        {
          name: "Demon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Dragon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "dragon",
          seen: false,
        },
        {
          name: "Treasure",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "ring",
          seen: false,
        },
        {
          name: "Gold",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "coin",
          seen: false,
        },
        {
          name: "Kru",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Gate",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "door",
          seen: false,
        },
        {
          name: "Ramparts",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "castle",
          seen: false,
        },
        {
          name: "Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
    {
      enabled: true,
      directions: { north: true, south: true, east: false, west: false },
      entities: [
        {
          name: "Sword",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Shield",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "shield",
          seen: false,
        },
        {
          name: "Helmet",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "armour",
          seen: false,
        },
        {
          name: "Knight",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "knight",
          seen: false,
        },
        {
          name: "Demon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Dragon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "dragon",
          seen: false,
        },
        {
          name: "Treasure",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "ring",
          seen: false,
        },
        {
          name: "Gold",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "coin",
          seen: false,
        },
        {
          name: "Kru",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Gate",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "door",
          seen: false,
        },
        {
          name: "Ramparts",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "castle",
          seen: false,
        },
        {
          name: "Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [
        {
          name: "Sword",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Shield",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "shield",
          seen: false,
        },
        {
          name: "Helmet",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "armour",
          seen: false,
        },
        {
          name: "Knight",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "knight",
          seen: false,
        },
        {
          name: "Demon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Dragon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "dragon",
          seen: false,
        },
        {
          name: "Treasure",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "ring",
          seen: false,
        },
        {
          name: "Gold",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "coin",
          seen: false,
        },
        {
          name: "Kru",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Gate",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "door",
          seen: false,
        },
        {
          name: "Ramparts",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "castle",
          seen: false,
        },
        {
          name: "Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
  ],
  [
    {
      enabled: false,
      directions: { north: false, south: false, east: false, west: false },
      entities: [
        {
          name: "Sword",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Shield",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "shield",
          seen: false,
        },
        {
          name: "Helmet",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "armour",
          seen: false,
        },
        {
          name: "Knight",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "knight",
          seen: false,
        },
        {
          name: "Demon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Dragon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "dragon",
          seen: false,
        },
        {
          name: "Treasure",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "ring",
          seen: false,
        },
        {
          name: "Gold",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "coin",
          seen: false,
        },
        {
          name: "Kru",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Gate",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "door",
          seen: false,
        },
        {
          name: "Ramparts",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "castle",
          seen: false,
        },
        {
          name: "Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
    {
      enabled: true,
      directions: { north: true, south: false, east: true, west: false },
      entities: [
        {
          name: "Sword",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Shield",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "shield",
          seen: false,
        },
        {
          name: "Helmet",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "armour",
          seen: false,
        },
        {
          name: "Knight",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "knight",
          seen: false,
        },
        {
          name: "Demon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Dragon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "dragon",
          seen: false,
        },
        {
          name: "Treasure",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "ring",
          seen: false,
        },
        {
          name: "Gold",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "coin",
          seen: false,
        },
        {
          name: "Kru",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Gate",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "door",
          seen: false,
        },
        {
          name: "Ramparts",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "castle",
          seen: false,
        },
        {
          name: "Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
    {
      enabled: true,
      directions: { north: false, south: false, east: false, west: true },
      entities: [
        {
          name: "Sword",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "sword",
          seen: false,
        },
        {
          name: "Shield",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "shield",
          seen: false,
        },
        {
          name: "Helmet",
          value: 3,
          type: "weapon",
          enabled: false,
          symbol: "armour",
          seen: false,
        },
        {
          name: "Knight",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "knight",
          seen: false,
        },
        {
          name: "Demon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "skeleton",
          seen: false,
        },
        {
          name: "Dragon",
          value: 3,
          type: "enemy",
          enabled: false,
          symbol: "dragon",
          seen: false,
        },
        {
          name: "Treasure",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "ring",
          seen: false,
        },
        {
          name: "Gold",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "coin",
          seen: false,
        },
        {
          name: "Kru",
          value: 3,
          type: "item",
          enabled: false,
          symbol: "key",
          seen: false,
        },
        {
          name: "Gate",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "door",
          seen: false,
        },
        {
          name: "Ramparts",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "castle",
          seen: false,
        },
        {
          name: "Lock",
          value: 3,
          type: "obstacle",
          enabled: false,
          symbol: "lock",
          seen: false,
        },
      ],
    },
  ],
];
